// <auto-generated />
using System;
using Association.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Association.Infrastructure.Migrations
{
    [DbContext(typeof(AssociationDbContext))]
    partial class AssociationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Association.Domain.AssociationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("Association.Domain.AssociationEntity", b =>
                {
                    b.OwnsOne("Association.Domain.AssociationIdentifier", "Identifier", b1 =>
                        {
                            b1.Property<Guid>("AssociationEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Identifier");

                            b1.HasKey("AssociationEntityId");

                            b1.ToTable("Associations");

                            b1.WithOwner()
                                .HasForeignKey("AssociationEntityId");
                        });

                    b.OwnsMany("Association.Domain.Membership", "Members", b1 =>
                        {
                            b1.Property<Guid>("AssociationID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("UserID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AssociationEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Role")
                                .HasColumnType("int");

                            b1.HasKey("AssociationID", "UserID");

                            b1.HasIndex("AssociationEntityId");

                            b1.ToTable("Memberships", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssociationEntityId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("AssociationEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("AssociationEntityId");

                            b1.ToTable("Associations");

                            b1.WithOwner()
                                .HasForeignKey("AssociationEntityId");
                        });

                    b.Navigation("Identifier")
                        .IsRequired();

                    b.Navigation("Members");

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
